package org.molina.jedilist;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import java.util.ArrayList;

public class ListActivity extends AppCompatActivity {

    /*Pasos para List View
    * Definir un layout para cada elemento
    * Crear la fuente de datos
    * Crear un Adapter
    * Conectar List View con el Adapter*/
    ArrayList<String> jediList = new ArrayList<>();
    ListView mListView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_list);

        mListView = findViewById(R.id.listView);
        loadJedis();

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(
                this,
                R.layout.list_item_jedi,
                R.id.txtJedi,
                jediList
        );

        mListView.setAdapter(adapter);

    }

    private void loadJedis(){
        jediList.add("Rajivari†");
        jediList.add("Garon Jard");
        jediList.add("Cala Brin");
        jediList.add("Ters Sendon");
        jediList.add("Nomi Sunrider");
        jediList.add("Kavar†");
        jediList.add("Zez-Kai Ell†");
        jediList.add("Vrook Lamar†");
        jediList.add("Loona Vash†");
        jediList.add("Vandar Tokare†");
        jediList.add("Dorjander Kace");
        jediList.add("Lucien Draay");
        jediList.add("Mical");
        jediList.add("Belth Allusis†");
        jediList.add("Otegω");
        jediList.add("Nikil Nobil");
        jediList.add("Wens Aleusis");
        jediList.add("Oric Traless");
        jediList.add("Giffis Fane");
        jediList.add("Syo Bakarn");
        jediList.add("Jaric Kaedan†");
        jediList.add("Bela Kiwiiks");
        jediList.add("Orgus Din†");
        jediList.add("Tol Braga");
        jediList.add("Shol Bestros");
        jediList.add("Barsen'thor");
        jediList.add("Yaddle†");
        jediList.add("Oppo Rancisis†");
        jediList.add("Omo Bouri†");
        jediList.add("Tor Difusal");
        jediList.add("Thame Cerulian†");
        jediList.add("T'un");
        jediList.add("Tyvokka†");
        jediList.add("Mace Windu†");
        jediList.add("Yarael Poof†");
        jediList.add("Micah Giiett†");
        jediList.add("Saesee Tiin†");
        jediList.add("Even Piell†");
        jediList.add("Eeth Kothω");
        jediList.add("Adi Gallia†");
        jediList.add("Plo Koon†");
        jediList.add("Depa Billabaω");
        jediList.add("Ki-Adi-Mundi†");
        jediList.add("Coleman Trebor†");
        jediList.add("Shaak Ti†");
        jediList.add("Kit Fisto†");
        jediList.add("Obi-Wan Kenobi†");
        jediList.add("Agen Kolar†");
        jediList.add("Coleman Kcajω");
        jediList.add("Stass Allie†");
        jediList.add("Barratk'I");
        jediList.add("Cilghal");
        jediList.add("Kyp Durron");
        jediList.add("Corran Horn");
        jediList.add("Mara Jade Skywalker†");
        jediList.add("Kyle Katarn");
        jediList.add("Tresina Lobi†");
        jediList.add("Octa Ramis");
        jediList.add("Jaina Solo Fel");
        jediList.add("Kam Solusar");
        jediList.add("Kol Skywalker†");
        jediList.add("T'raa Saaω†");
        jediList.add("Tili Qua");
        jediList.add("K'Kruhkω");
        jediList.add("Vodo-Siosk Baas†");
        jediList.add("Vima Sunrider");
        jediList.add("Q'Anilia†");
        jediList.add("Hoth†");
        jediList.add("Valenthyne Farfalla†");
        jediList.add("Arca Jeth†");
        jediList.add("Arren Kae†");
        jediList.add("Kavar†");
        jediList.add("Zhar Lestin†");
        jediList.add("Ooroo†");
        jediList.add("Quatra");
        jediList.add("Thon");
        jediList.add("Meetra Surik†");
        jediList.add("Brianna");
        jediList.add("Caudle");
        jediList.add("Dookuω");
        jediList.add("Cin Drallig†");
        jediList.add("Nejaa Halcyon†");
        jediList.add("Ikritω†");
        jediList.add("Qui-Gon Jinn†");
        jediList.add("Volfe Karkko");
        jediList.add("Maks Leem†");
        jediList.add("Saras Loorne†");
        jediList.add("Thracia Cho Leem");
        jediList.add("Jai Maruk†");
        jediList.add("Nat-Sem†");
        jediList.add("Echuu-Shen Jon†");
        jediList.add("Sifo-Dyas†");
        jediList.add("Tahl†");
        jediList.add("Kao Cen Darach†");
        jediList.add("Celeste Morne†");
        jediList.add("Siri Tachi†");
        jediList.add("Jorus C'baoth†");
        jediList.add("Kossex");
        jediList.add("Sidrona Diath†");
        jediList.add("Revan");
        jediList.add("Dar'Nala†");
        jediList.add("Tholme†");
        jediList.add("K'Kruhk");
        jediList.add("Tycho");
        jediList.add("Luminara Unduli†");
        jediList.add("Quinlan Vos");
        jediList.add("Aayla Secura†");
        jediList.add("Zao");
        jediList.add("Aqinosω†");
        jediList.add("Te Corso†");
        jediList.add("Anakin Skywalker†");
        jediList.add("Asaak Dan");
        jediList.add("Drok†");
        jediList.add("Sayar Dun'La†");
        jediList.add("Eelysa†");
        jediList.add("Hira†");
        jediList.add("Lar Le'Ung†");
        jediList.add("Mai");
        jediList.add("Markre Medjev");
        jediList.add("Wolf Sazen†");
        jediList.add("Nat Skywalker†");
        jediList.add("Streen");
        jediList.add("Tobias Sun");
        jediList.add("Kirana Ti");
        jediList.add("Rasi Tuum");
        jediList.add("Shado Vao");
        jediList.add("X2");
        jediList.add("Mander Zuma");
        jediList.add("Rahm Kota");
        jediList.add("Cay Qel-Droma†");
        jediList.add("Ulic Qel-Droma†");
        jediList.add("Duron Qel-Droma†");
        jediList.add("Andur Sunrider†");
        jediList.add("Tott Doneeta");
        jediList.add("Bastila Shan");
        jediList.add("Oss Wilum");
        jediList.add("Belaya");
        jediList.add("Shaela Nuur†");
        jediList.add("Barrison Draay†");
        jediList.add("Cale Berkona");
        jediList.add("Sylvar");
        jediList.add("Aidan Bok†");
        jediList.add("Ambaln");
        jediList.add("Bultar Swan†");
        jediList.add("Sharad Hett†");
        jediList.add("Ky Narec†");
        jediList.add("Lorana Jinzler†");
        jediList.add("Barriss Offee†");
        jediList.add("Alfi †");
        jediList.add("Turi Altamik");
        jediList.add("Avinoam Arelis");
        jediList.add("Tash Arranda");
        jediList.add("Zak Arranda");
        jediList.add("Daye Azur-Jamin");
        jediList.add("Tam Azur-Jamin");
        jediList.add("Kunor Bann");
        jediList.add("Serra Keto†");
        jediList.add("Eryl Besa †");
        jediList.add("Empatojayos Brand † ω");
        jediList.add("Yantahar Bwua'tu");
        jediList.add("Hivrekh'wao'Cheklev");
        jediList.add("Chitter");
        jediList.add("Vima-Da-Boda ω");
        jediList.add("Daeshara'cor †");
        jediList.add("Damaya");
        jediList.add("Nelani Dinn †");
        jediList.add("Dordi");
        jediList.add("Dorsk 81 †");
        jediList.add("Dorsk 82 †");
        jediList.add("Seha Dorvald");
        jediList.add("Jovan Drark †");
        jediList.add("Fahjay");
        jediList.add("Keyan Farlander");
        jediList.add("Swilja Fenn †");
        jediList.add("Klin-Fa Gi");
        jediList.add("Kento Marek");
        jediList.add("Bela Hara †");
        jediList.add("Krasov Hara †");
        jediList.add("Harlan");
        jediList.add("Hedda †");
        jediList.add("Seff Hellin");
        jediList.add("Valin Horn");
        jediList.add("Jysella Horn");
        jediList.add("Huli");
        jediList.add("Kolir Hu'lya");
        jediList.add("Ilum ω");
        jediList.add("Tresk Im'nel");
        jediList.add("Toro Irana †");
        jediList.add("Seyyerin Itoklo †");
        jediList.add("Jayk");
        jediList.add("Jerga †");
        jediList.add("Jorallen");
        jediList.add("Waxarn Kel");
        jediList.add("Ulaha Kore †");
        jediList.add("Jaden Korr");
        jediList.add("Kubariet †");
        jediList.add("Lassin †");
        jediList.add("Drif Lij †");
        jediList.add("Loli †");
        jediList.add("Lowbacca");
        jediList.add("Lusa †");
        jediList.add("Tensh Ly'alu");
        jediList.add("Lyric †");
        jediList.add("Madurrin");
        jediList.add("Nichos Marr † ω");
        jediList.add("Cray Mingla †");
        jediList.add("Radd Minker");
        jediList.add("Thann Mithric †");
        jediList.add("Kelbis Nu †");
        jediList.add("Ozlo †");
        jediList.add("Rosh Penin");
        jediList.add("Raltharan");
        jediList.add("Ramud");
        jediList.add("Numa Rar †");
        jediList.add("Vaala Razelle");
        jediList.add("Miko Reglia †");
        jediList.add("Ganner Rhysode †");
        jediList.add("Rivai");
        jediList.add("Sothais Saar");
        jediList.add("Yaqeel Saav'etu");
        jediList.add("Tesar Sebatyne");
        jediList.add("Toile Senn †");
        jediList.add("Wurth Skidder †");
        jediList.add("Ben Skywalker");
        jediList.add("Corask Slen'da");
        jediList.add("Anakin Solo †");
        jediList.add("Leia Organa Solo");
        jediList.add("Doran Sarkin-Tainer");
        jediList.add("Tyria Sarkin Tainer");
        jediList.add("Tekli");
        jediList.add("Raynar Thul");
        jediList.add("Sanola Ti");
        jediList.add("Hosk Trey'lis †");
        jediList.add("Thrynni Vae †");
        jediList.add("Ahn Rasi Tuum †");
        jediList.add("Zho Rasi Tuum");
        jediList.add("Twool †");
        jediList.add("Tahiri Veila");
        jediList.add("Shul Vaal");
        jediList.add("Vis'l †");
        jediList.add("Natua Wan †");
        jediList.add("Bazel Warv †");
        jediList.add("Izal Waz");
        jediList.add("Wilyem");
        jediList.add("Wonetun");
        jediList.add("Yabeley †");
        jediList.add("Jem Ysanna †");
        jediList.add("Rayf Ysanna †");
        jediList.add("Yuledan †");
        jediList.add("Zal");
        jediList.add("Tiu Zax");
        jediList.add("Zekk");
    }
}
